on:
  push:
  pull_request:
  workflow_dispatch:

name: Install dep with upper bound

jobs:

  # Install dependencies directly with pak
  use-pak:
    runs-on: ${{ matrix.os }}
    name: use-action (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
      - name: Install pak
        run: install.packages("pak")
        shell: Rscript {0}
      - name: Install dependencies
        run: pak::pak()
        shell: Rscript {0}

  # Install dependencies with setup-r-dependencies
  use-action:
    runs-on: ${{ matrix.os }}
    name: use-action (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
